#!/usr/bin/env python
"""
manage.py
---------
This is Django's command-line utility for administrative tasks.

WHY THIS FILE EXISTS:
Every Django project needs a single entry point to run management
commands such as:
    python manage.py runserver      -> starts the development web server
    python manage.py migrate        -> applies database migrations
    python manage.py makemigrations -> creates new migration files
    python manage.py createsuperuser-> creates an admin login

You almost never need to edit this file. It is auto-generated by
Django when you run "django-admin startproject".
"""
import os
import sys


def main():
    """
    The main() function is the entry point of this script.
    It tells Django which settings file to use, and then hands
    control over to Django's command-line management system.
    """
    # DJANGO_SETTINGS_MODULE tells Django where to find settings.py
    # "inventory_project.settings" means: look inside the
    # inventory_project folder, for a file called settings.py
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'inventory_project.settings')
    try:
        # execute_from_command_line() reads the command typed in the
        # terminal (like "runserver" or "migrate") and executes it.
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        # This error usually means Django is not installed, or the
        # virtual environment is not activated.
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    # sys.argv is the list of arguments typed in the terminal.
    # Example: ["manage.py", "runserver"]
    execute_from_command_line(sys.argv)


# This standard Python check ensures main() only runs when this file
# is executed directly (python manage.py ...), not when imported.
if __name__ == '__main__':
    main()
