"""
forms.py
--------
This file defines the FORMS used to create/edit Product records.

WHY USE ModelForm INSTEAD OF A PLAIN Form OR RAW HTML <input> TAGS?
--------------------------------------------------------------------
1. ModelForm automatically generates form fields FROM the model, so
   we don't repeat field names/types twice (once in models.py and
   again in forms.py). If we add a new field to the model, the form
   updates automatically.
2. ModelForm gives us FREE VALIDATION - e.g. it automatically checks
   that 'price' is a valid decimal and 'quantity' is a non-negative
   integer, matching the constraints already defined on the model.
3. ModelForm provides a save() method that directly creates/updates
   the database row for us (form.save()), so we don't have to
   manually pull each field out of request.POST and assign it.
4. It automatically protects against basic bad input, and works
   seamlessly with Django's CSRF protection when rendered in a
   template with {% csrf_token %}.
"""
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    """
    ProductForm is tied to the Product model. It is used for BOTH
    adding a new product and updating an existing one (the same
    form class is reused in the add_product and update_product views).
    """

    class Meta:
        # Meta tells Django "build this form's fields based on the
        # Product model, and only include these specific fields".
        model = Product
        fields = ['name', 'category', 'quantity', 'price', 'supplier']
        # Note: 'id' and 'created_at' are deliberately excluded.
        # 'id' is auto-generated by the database, and 'created_at'
        # is auto-set by auto_now_add=True - neither should be
        # editable by the user through a form.

        # widgets let us customise the HTML attributes of each
        # rendered <input> field (e.g. adding CSS classes or
        # placeholder text) without writing raw HTML by hand.
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter product name'
            }),
            'category': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter category (e.g. Electronics)'
            }),
            'quantity': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter quantity in stock'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter price per unit',
                'step': '0.01'
            }),
            'supplier': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter supplier name'
            }),
        }
