# Generated by Django 4.2.30 on 2026-07-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the product, e.g. 'Wireless Mouse'",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category of the product, e.g. 'Electronics'",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of units currently in stock"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        help_text="Name of the supplier/vendor who supplies this product",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
