"""
urls.py (PROJECT LEVEL)
------------------------
This is the master URL configuration for the whole Django project.
When a request comes in (e.g. someone visits /products/), Django
starts here, at ROOT_URLCONF (set in settings.py), and tries to
match the URL against the patterns in urlpatterns below.

WHY include()?
--------------
Instead of writing every single URL pattern in this one file, we use
include() to "hand off" any URL that isn't /admin/ to our inventory
app's own urls.py. This keeps things modular - each app manages its
own URLs, which is the standard Django convention.
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # /admin/ -> Django's built-in admin site (auto-generated by Django)
    path('admin/', admin.site.urls),

    # Every other URL ('', 'login/', 'products/', etc.) is delegated
    # to the inventory app's urls.py file.
    path('', include('inventory.urls')),
]
